source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

use_frameworks!

target 'iosApp' do

  pod 'kbcore',
    :git => 'https://github.com/dariuszszlag/KBMultiplatform.git', :tag => '1.2.0'

end
