name: Create KBCore (iOS)
on:
  push:
    tags:
      - "v*.*.*-core-iOS"

  workflow_dispatch:

jobs:
  kmmbridgepublish:
    name: Create KBCore for iOS with KMMBridge
    concurrency: "kmmbridgepublish-${{ github.repository }}"
    runs-on: macos-latest
    steps:
      - name: Create random ID for branch name
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1.1

      - name: Create random branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_CODE }}
        with:
          branch: "build-${{ steps.generate-uuid.outputs.uuid }}"

      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: "build-${{ steps.generate-uuid.outputs.uuid }}"

      - name: Change wrapper permissions
        run: chmod +x ./generate-version.bash

      - name: Set tag version as env variable
        run: ./generate-version.bash

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Release
        run: ./gradlew :kbcore:kmmBridgePublish -PENABLE_PUBLISHING=true -PGIT_USER=${{ github.actor }} -PGITHUB_PUBLISH_TOKEN=${{ secrets.SECRET_GITHUB_CODE }} -PGITHUB_REPO=${{ github.repository }} --no-daemon --stacktrace

      - name: Delete branch
        if: always()
        uses: touchlab/action-delete-branch@v3
        with:
          github_token: ${{ secrets.SECRET_GITHUB_CODE }}
          branches: "build-${{ steps.generate-uuid.outputs.uuid }}"