name: Create KBCore for Apple release

on:
  push:
    tags:
      - "v*.*.*-IOS"

  workflow_dispatch:

jobs:
  publish:
    name: Release KBCore
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Publish KBCore for iOS
        run: pod trunk push kbcore/KBCore.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_GITHUB_SECRET }}

