name: Create KBCore (iOS)

on:
  push:
    tags:
      - "v*.*.*-core-iOS"

  workflow_dispatch:

jobs:
  publish:
    name: Release KBCore
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change wrapper permissions
        run: chmod +x ./generate-version.bash

      - name: Set tag version as env variable
        run: ./generate-version.bash

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Publish XCFramework for iOS
        run: |
          ./gradlew :kbcore:podspec
          ./gradlew :kbcore:podImport
          ./gradlew :kbcore:podInstall
          ./gradlew :kbcore:podPublishXCFramework

